---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - curl
      - vim
      - git
      - ufw
      - fail2ban
    state: present

- name: Enable UFW firewall
  ufw:
    state: enabled
    rule: allow
    port: ssh
